import localFont from "next/font/local";
import ".././globals.css";
import {
  ClerkProvider,
  RedirectToSignIn,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs';
import LeftLayout from "@/components/LeftLayout";
import RightLayout from "@/components/RightLayout";




const geistSans = localFont({
  src: ".././fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: ".././fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >


          <div className="flex justify-between max-w-6xl m-5">
              <div className="sm:inLine h-screen sticky top-0 w-[18rem]"> 
                  <LeftLayout />
                </div>
                <div className="max-w-3xl flex-1">{children}</div>
                <div className="lg:flex-col p-3 h-screenhidden lg:flex">
                  <RightLayout />
                </div>

          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
